#!/bin/bash

# Please don't change this.
MAX_POINTS=150

# Function check for task 1
test_servere() {
	n_tests=25
	src_names=(servere.c servere.cpp Servere.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem servere 1
}

# Function check for task 2
test_colorare() {
	n_tests=25
	src_names=(colorare.c colorare.cpp Colorare.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem colorare 2
}

# Function check for task 3
test_compresie() {
	n_tests=25
	src_names=(compresie.c compresie.cpp Compresie.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem compresie 3
}

# Function check for task 4
test_criptat() {
	n_tests=30
	src_names=(criptat.c criptat.cpp Criptat.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=30

	run_problem criptat 4
}

# Function check for task 5
test_oferta() {
	n_tests=35
	src_names=(oferta.c oferta.cpp Oferta.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=35

	run_problem oferta 5
}

# Put your tasks in this function
test_homework() {
	if [[ "$1" = "1" || "$1" = "servere" ]]; then
		test_servere
	elif [[ "$1" = "2" || "$1" = "colorare" ]]; then
		test_colorare
	elif [[ "$1" = "3" || "$1" = "compresie" ]]; then
		test_compresie
	elif [[ "$1" = "4" || "$1" = "criptat" ]]; then
		test_criptat
	elif [[ "$1" = "5" || "$1" = "oferta" ]]; then
		test_oferta
	elif [[ "$1" = "cs" ]]; then
		echo "skip running tests"
	else
		test_servere
		test_colorare
		test_compresie
		test_criptat
		test_oferta
	fi
}

# Define bonus task
BONUS_TASK=oferta

# Please don't change this.
source "$(dirname "{0}")"/_utils/base_check.sh
