#!/bin/bash

# Please don't change this.
MAX_POINTS=150

# Function check for task 1
test_numarare() {
	n_tests=35
	src_names=(numarare.c numarare.cpp Numarare.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=35

	run_problem numarare 1
}

# Function check for task 2
test_trenuri() {
	n_tests=40
	src_names=(trenuri.c trenuri.cpp Trenuri.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=40

	run_problem trenuri 2
}

# Function check for task 3
test_drumuri() {
	n_tests=40
	src_names=(drumuri.c drumuri.cpp Drumuri.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=40

	run_problem drumuri 3
}

# Function check for task 4 (bonus)
test_scandal() {
	n_tests=25
	src_names=(scandal.c scandal.cpp Scandal.java)
	tests=($(seq 0 $(($n_tests - 1))))
	points=($(printf '1.0 %.0s' $(seq 0 $(($n_tests - 1)))))
	pmax=25

	run_problem scandal 4
}

# Put your tasks in this function
test_homework() {
	if [[ "$1" = "1" || "$1" = "numarare" ]]; then
		test_numarare
	elif [[ "$1" = "2" || "$1" = "trenuri" ]]; then
		test_trenuri
	elif [[ "$1" = "3" || "$1" = "drumuri" ]]; then
		test_drumuri
	elif [[ "$1" = "4" || "$1" = "scandal" ]]; then
		test_scandal
	elif [[ "$1" = "cs" ]]; then
		echo "skip running tests"
	else
		test_numarare
		test_trenuri
		test_drumuri
		test_scandal
	fi
}

# Define bonus task
BONUS_TASK=scandal

# Please don't change this.
source "$(dirname "{0}")"/_utils/base_check.sh
